<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'CleanArchitectureNetCore' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.12" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.12" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.2.0" />
    <PackageReference Include="SoftoSol.SoftoExceptions" Version="1.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Microsoft.AspNetCore.Mvc.Versioning" />
    <None Remove="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CleanArchitectureNetCore.Common\CleanArchitectureNetCore.Common.csproj" />
    <ProjectReference Include="..\CleanArchitectureNetCore.Infrastructure.Persistence\CleanArchitectureNetCore.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\CleanArchitectureNetCore.Infrastructure\CleanArchitectureNetCore.Infrastructure.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\CleanArchitectureNetCore.Application\CleanArchitectureNetCore.Application.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\CleanArchitectureNetCore.Domain\CleanArchitectureNetCore.Domain.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
</Project>
